### ISSUE TITLE
1) Power

### ISSUE THREAD

**Issue by zafienas** [zafienas/SSK3101-G14-2021#21]
### Problem Definition:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/73152790/123617138-8588c280-d839-11eb-9a6a-20d48896dd00.png">

### Submission:

1. Source Code
2. Output

### Dateline: 30 June 2021 (Wednesday)

**Comment by Kelly0621** [comment]
1. Source code
```java
package Lab09_Ques1;

import java.util.Scanner;

public class RecursiveFunction {

/* Developer: Kelly Pang Li Xiang
 * No. Matric: 205851
 * Create RecursiveFunction Class with power method*/
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner input=new Scanner(System.in);
		System.out.println("Enter x");
		int x=input.nextInt();
		System.out.println("Enter y");
		int y=input.nextInt();
		System.out.printf("%.4f",power(x,y));
		input.close();
	}
	public static double power(int x,int y) {
		if(y==0)
			return 1;// x power 0 = 1
		else if (y==1)
			return x;// x power 1 = x
		else if (y<0)
			return 1/power(x,-y);
		else
		return x*power(x,y-1);
	}
}
```
2. Output
a) if y=0
![image](https://user-images.githubusercontent.com/81618601/123625154-09df4380-d842-11eb-8a3a-0c5d263aef23.png)
b) if y=1
![image](https://user-images.githubusercontent.com/81618601/123631272-216dfa80-d849-11eb-8034-1c32f8579b9d.png)
c) if y>1
![image](https://user-images.githubusercontent.com/81618601/123631389-495d5e00-d849-11eb-8444-d877749c8619.png)
d) if y<0
![image](https://user-images.githubusercontent.com/81618601/123631331-3480ca80-d849-11eb-832e-d7582c9e562b.png)

**Comment by Calvin0309** [comment]
1. Source code:
```ruby
//developer: Calvin Low Chee Seng
//Matrik no: 208006

import java.util.Scanner;
public class Power {
	public static void main(String ags[]) {
		Scanner sc=new Scanner(System.in);
		System.out.println("Key in base");
		int x=sc.nextInt();
		System.out.println("Key in power");
		int y=sc.nextInt();
		System.out.println(power(x,y));
		}
	
	public static double power(double x,double y) {
		if (y==0) 
			return 1;
		else if(y==1) 
			return x;
		else if(y>1) 
			return x*power(x,y-1);
		else 
			return 1/power(x,-y);
		}
}
```
2.Output:
![image](https://user-images.githubusercontent.com/77290398/123625987-e963b900-d842-11eb-9908-692de46c747d.png)
![image](https://user-images.githubusercontent.com/77290398/123626043-f7b1d500-d842-11eb-9797-2848b7510eca.png)
![image](https://user-images.githubusercontent.com/77290398/123626075-01d3d380-d843-11eb-8637-d0260104005c.png)
![image](https://user-images.githubusercontent.com/77290398/123626116-0d26ff00-d843-11eb-9655-154bd958e3da.png)

**Comment by huiyi429** [comment]
1.
```java
import java.util.Scanner;

public class Power {
	
public static void main (String []args) {
	Scanner input=new Scanner(System.in);
	System.out.print("Enter x and y:");
	int a= input.nextInt();
	int b= input.nextInt();
	System.out.println("x^y: "+power(a,b));
	
	input.close();
	
}
public static double power(int x, int y) {
	double result=10;
	
	if (y==0) {
		result= 1;
	}else if(y==1) {
		result= x;
	}else if(y>1) {
		result= x*power(x,y-1);
	}else if(y<0) {
		result=1/(power(x,-y));
		}return result;
} }
```
2. Output
![image](https://user-images.githubusercontent.com/81619434/123626379-5f682000-d843-11eb-99cc-c876041ede31.png)
![image](https://user-images.githubusercontent.com/81619434/123626413-68f18800-d843-11eb-944f-0c3dbf2b960d.png)
![image](https://user-images.githubusercontent.com/81619434/123626433-73138680-d843-11eb-880d-7e576a37ee2b.png)
![image](https://user-images.githubusercontent.com/81619434/123626255-38115300-d843-11eb-9149-c0f1021f31e1.png)

**Comment by syahiraazhari** [comment]
1. Source Code

```java
package Question_1;

//Developer: Syahira Izazi binti Azhari
//Matric No: 208351

public class Power_Function {
    
    //Declare method power to return value of x^y
    public static double power(double x, double y) {
        
            if (y == 0) //y = 0
                return 1;
            
            else if (y == 1) //y = 1
                return x;
            
            else if (y > 1) // Positive y, bigger than 1
                return x*power(x, y-1); //Recall power method
            
            else //Negative y
                return 1/power(x, -y); //Recall power method
    
     }
    
    public static void main(String[] args) {
	
        //Print output of x^y
        System.out.println("Answer: " + power(3, 4));
        
    }
}
```


2. Output

a) x = 3, y = 0 

![image](https://user-images.githubusercontent.com/81618699/123626917-efa66500-d843-11eb-8e3f-cde6f3bf4591.png)

b) x = 3, y = 1

![image](https://user-images.githubusercontent.com/81618699/123626872-e1f0df80-d843-11eb-905f-26ff73bf64e4.png)

c) x = 3, y = 4 (Positive y, bigger than 1)

![image](https://user-images.githubusercontent.com/81618699/123626612-9b9b8080-d843-11eb-8c3d-911b9c98e587.png)

d) x = 3, y = -4 (Negative y)

![image](https://user-images.githubusercontent.com/81618699/123626811-d1d90000-d843-11eb-95e2-6f98cac9d5ae.png)

**Comment by Zarifah207966** [comment]
1. Coding
```java
//Zarifah Zaifiera binti Zainal
//207966
public class q1 {

	public static double power(int x, int y) {
		if (y == 0) {
			return 1;
		}else if(y == 1) {
			return x;
		}else if (y > 1) {
			return x*power(x, y-1);
		}else {
			return 1/power(x, -y);
		}
	}
	
	public static void main(String[] args) {
		double result = power(2,-3);
		System.out.println(result);
		
	}
}
```
2.Output
x = 2, y = 0
![image](https://user-images.githubusercontent.com/81618631/123628321-8889b000-d845-11eb-9aa7-cadd27d0ff8e.png)

x=2, y=1
![image](https://user-images.githubusercontent.com/81618631/123628361-950e0880-d845-11eb-9173-0f470b874e8e.png)

x=2, y=3
![image](https://user-images.githubusercontent.com/81618631/123628411-a3f4bb00-d845-11eb-8085-b641b070dd18.png)

x=2, y=-3
![image](https://user-images.githubusercontent.com/81618631/123628449-b0791380-d845-11eb-8a49-79a5fc0d02c7.png)

**Comment by AinNadhirah-206090** [comment]
1) Source Code : 
``` java
// developer : Nur Ain Nadhirah binti Zulkifli
// Matric No : 206090

import java.util.Scanner;

public class powerRec {

	public static void main(String[] args) {
		Scanner scan = new Scanner (System.in);
		System.out.println(" Enter two number :");
		int x = scan.nextInt();
		int y = scan.nextInt();
	
		double result = power(x, y);
		System.out.println();
		System.out.println(x + " power of " + y + " is " +result);
		
	}
	
	public static double power(int x, int y) {
		if(y == 0) {
			return 1;
		}
		
		else if (y == 1) {
			return x;
		}
		
		else if (y > 1) {
			return x*power(x,y-1);
		}
		
		else {
			return 1/power(x, -y);
		}
			
	}

}

```

2) Output : 
(i) y = 0
![y zero](https://user-images.githubusercontent.com/81618743/123630466-267e7a00-d848-11eb-8df8-7093125bd05f.PNG)

(ii) y = 1
![y one ](https://user-images.githubusercontent.com/81618743/123630518-36965980-d848-11eb-9547-9cf6530f876b.PNG)

(iii) y > 0
![powerRec](https://user-images.githubusercontent.com/81618743/123630580-4877fc80-d848-11eb-9936-66e8593109b2.PNG)

(iv) y < 0
![y neg](https://user-images.githubusercontent.com/81618743/123630615-52016480-d848-11eb-8114-5e9c8dd6ef67.PNG)

**Comment by tjiamin0112** [comment]
Coding
```java
package lab9;

//Developer: Tan Jia Min
//Matric no: 205453

import java.util.Scanner;

public class Lab9Ques1 {
	public static void main(String[]args) {
		Scanner input = new Scanner(System.in);
		//Prompt user to input
		System.out.print("Please enter int x (base): ");
		int x = input.nextInt();
		System.out.print("Please enter int y (power): ");
		int y = input.nextInt();
		input.close();
		
		//invoke the recursive function
		power(x,y);
		
		//Display the result 
		System.out.println("The result of x^y is " + power(x,y));
	}
	
	//Return the result
	public static double power(int x, int y) {
		if (y==0) { //y=0
			return 1; //base case
		}
		else if (y==1) { //y=1
			return x; //base case
		}
		else if (y>1) { //y>1
			return x*power(x,y-1); //recursive call
		}
		else // y<0
			return 1/power(x,-y); //recursive call
	}
}
```
Output
y=0
![image](https://user-images.githubusercontent.com/81618817/123653255-82330e00-d81c-11eb-8065-d00a74a5159a.png)

y=1
![image](https://user-images.githubusercontent.com/81618817/123653278-87905880-d81c-11eb-9379-c49d9fe5209e.png)

y>1
![image](https://user-images.githubusercontent.com/81618817/123653301-8b23df80-d81c-11eb-982e-94bb369942c0.png)

y<0
![image](https://user-images.githubusercontent.com/81618817/123653347-94ad4780-d81c-11eb-886d-2fb3baf0bb1d.png)

**Comment by amir2511** [comment]
1) Code
```java
//Amir Azian bin Alias
//206119

import java.util.Scanner;

public class Question1Power {

	public static void main(String[] args) {
		
		Scanner am = new Scanner(System.in);
		
		System.out.print( "Enter number : " );
		int num = am.nextInt();
		System.out.print( "Enter power : " );
		int power = am.nextInt();
		
		double result = power( num, power);
		System.out.println( num + " power of " + power + " : " +result);
		
		

	}
	
	public static double power( int x, int y ) {
		
		if ( y==0 ) {
			return 1;
		}
		
		else if ( y==1 ) {
			return x;
		}
		
		else if ( y>1 ) {
			return x*power(x,y-1);
		}
		
		else {
			return 1/power(x, -y);
		}
		
	}

}
```

2) Output
![image](https://user-images.githubusercontent.com/81618647/123741828-eb765800-d8d4-11eb-89e5-50e5b4cd121b.png)
![image](https://user-images.githubusercontent.com/81618647/123741965-24163180-d8d5-11eb-8401-d355aebc3d55.png)
![image](https://user-images.githubusercontent.com/81618647/123742000-31cbb700-d8d5-11eb-9f7f-cfc961239e43.png)
![image](https://user-images.githubusercontent.com/81618647/123742064-4ad46800-d8d5-11eb-8f4d-98752af55cf4.png)

**Comment by aaisyasofia** [comment]
1) Code
```java
//Developer: AISYA SOFIA BINTI ISMAIL
//No Matric: 208036
import java.util.Scanner;

public class power {

	public static void main(String[] args) {
		
		Scanner input = new Scanner(System.in);
		System.out.println("Value of x: ");
		int x = input.nextInt();
		System.out.println("Value of y: ");
		int y = input.nextInt();
		
		double result = power(x,y);
		System.out.println("Result: " + result);
	}
	public static double power( int x, int y) {
		if ( y == 0 ) {
			return 1;
		}
		else if ( y == 1) {
			return x;
		}
		else if ( y > 1 ) {
			return x*power(x, y-1);
		}
		else {
			return 1/power(x,-y);
		}
		}}
```
2) Output
![image](https://user-images.githubusercontent.com/81618607/123817219-8baa9c00-d92a-11eb-8d73-8001b987bed3.png)
![image](https://user-images.githubusercontent.com/81618607/123817281-97965e00-d92a-11eb-9c2c-cf793807ef2f.png)
![image](https://user-images.githubusercontent.com/81618607/123817330-a4b34d00-d92a-11eb-8e11-0bf0f4b057d6.png)
![image](https://user-images.githubusercontent.com/81618607/123817371-ae3cb500-d92a-11eb-8bc3-1f085fd4c6b8.png)

**Comment by nurnadhirah311** [comment]
1. Code
```java
//Name:NUR NADHIRAH BINTI KAMARUDIN
//No Matric:205415
import java.util.Scanner;
public class Ques1 {
  public static void main(String[] args) {
		
      Scanner sc = new Scanner(System.in);
      System.out.println("Enter integer of x:");
      int x = sc.nextInt();
      System.out.println("Enter integer of y:");
      int y = sc.nextInt();
		
      double result = power(x,y);
      System.out.println("Result: " + result);
   }
	
  public static double power( int x, int y) {
	if ( y == 0 ) {
            return 1;
	}
        else if ( y == 1) {
            return x;
	}
	else if ( y > 1 ) {
	    return x*power(x, y-1);
	}
        else {
	    return 1/power(x,-y);
	}
  }
}
```

2. Output
![image](https://user-images.githubusercontent.com/81213840/123900292-686c0500-d99b-11eb-85b9-04d89cd2bced.png)
![image](https://user-images.githubusercontent.com/81213840/123900442-a9641980-d99b-11eb-9648-6a82e1fb6672.png)
![image](https://user-images.githubusercontent.com/81213840/123900572-df090280-d99b-11eb-98bd-f7a475645431.png)
![image](https://user-images.githubusercontent.com/81213840/123900666-0bbd1a00-d99c-11eb-9da2-962eb277b2d9.png)
